In [973]:
import pandas as pd
import numpy as np

## Academico

In [974]:
data_aca_2023 = pd.read_csv('../data/academico_2023.csv', encoding='latin1', sep=';')
data_aca_2024 = pd.read_csv('../data/academico_2024.csv', encoding='latin1', sep = ';')

C:\Users\jange\AppData\Local\Temp\ipykernel_65780\129942648.py:1: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  data_aca_2023 = pd.read_csv('../data/academico_2023.csv', encoding='latin1', sep=';')

In [975]:
data_aca_2023.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44581 entries, 0 to 44580
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   anio                   44581 non-null  int64
 1   region_ie              44581 non-null  object
 2   provincia_ie           44581 non-null  object
 3   ugel_ie                44581 non-null  object
 4   distrito_ie            44581 non-null  object
 5   centropoblado_ie       44581 non-null  object
 6   institucion_educativa  44581 non-null  object
 7   codigolocal_ie         44581 non-null  int64
 8   codigomodular_ie       44581 non-null  int64
 9   ruralidad              44581 non-null  object
 10  estudiantes            44581 non-null  object
 11  grado                  44581 non-null  object
 12  periodo                44581 non-null  object
 13  curso                  44581 non-null  object
 14  comp                   44581 non-null  object
 15  nivel_de_logro         44581 non-null  object
 16  dni_participante       44517 non-null  object
 17  id_participante        44581 non-null  object
 18  participante           44581 non-null  object
 19  coordinador_a          44581 non-null  object
 20  programa               44581 non-null  object
 21  anio_pdl               44581 non-null  object
 22  socios                 44581 non-null  object
dtypes: int64(3), object(20)
memory usage: 7.8+ MB

In [976]:
data_aca_2023.programa.value_counts()

programa
PDL    25367
QM     19214
Name: count, dtype: int64

In [977]:
data_aca_2023 = data_aca_2023.loc[data_aca_2023.programa == 'PDL']

In [978]:
data_aca_2023.id_participante.nunique()

145

In [979]:
data_aca_2024.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51556 entries, 0 to 51555
Data columns (total 25 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   anio                   51556 non-null  int64
 1   region_ie              51556 non-null  object
 2   provincia_ie           51556 non-null  object
 3   ugel_ie                51556 non-null  object
 4   distrito_ie            51556 non-null  object
 5   centropoblado_ie       51556 non-null  object
 6   institucion_educativa  51556 non-null  object
 7   codigolocal_ie         51556 non-null  int64
 8   codigomodular_ie       51556 non-null  int64
 9   ruralidad              51556 non-null  object
 10  estudiantes            51556 non-null  object
 11  grado                  51556 non-null  object
 12  periodo                51556 non-null  object
 13  curso                  51556 non-null  object
 14  comp                   51556 non-null  object
 15  nivel_de_logro         51556 non-null  object
 16  dni_participante       51556 non-null  int64
 17  id_participante        51556 non-null  object
 18  participante           51556 non-null  object
 19  coordinador_a          51556 non-null  object
 20  programa               51556 non-null  object
 21  anio_pdl               51556 non-null  object
 22  socios                 43820 non-null  object
 23  id_seccion             51556 non-null  object
 24  tipo                   48482 non-null  object
dtypes: int64(4), object(21)
memory usage: 9.8+ MB

In [980]:
data_aca_2024.programa.value_counts()

programa
QM               25135
PDL              18685
Palanca 1 y 2     7736
Name: count, dtype: int64

In [981]:
data_aca_2024 = data_aca_2024.loc[~data_aca_2024['programa'].isin(['Palanca 1 y 2'])]

In [982]:
data_aca_2024 = data_aca_2024.loc[data_aca_2024.programa == 'PDL']

In [983]:
data_aca_2024.id_participante.nunique()

93

In [984]:
data_aca_2023.estudiantes.nunique()

4385

In [985]:
data_aca_2024.estudiantes.nunique()

2359

In [986]:
data_aca_2023.columns

Index(['anio', 'region_ie', 'provincia_ie', 'ugel_ie', 'distrito_ie',
       'centropoblado_ie', 'institucion_educativa', 'codigolocal_ie',
       'codigomodular_ie', 'ruralidad', 'estudiantes', 'grado', 'periodo',
       'curso', 'comp', 'nivel_de_logro', 'dni_participante',
       'id_participante', 'participante', 'coordinador_a', 'programa',
       'anio_pdl', 'socios'],
      dtype='object')

In [987]:
data_aca_2024.columns

Index(['anio', 'region_ie', 'provincia_ie', 'ugel_ie', 'distrito_ie',
       'centropoblado_ie', 'institucion_educativa', 'codigolocal_ie',
       'codigomodular_ie', 'ruralidad', 'estudiantes', 'grado', 'periodo',
       'curso', 'comp', 'nivel_de_logro', 'dni_participante',
       'id_participante', 'participante', 'coordinador_a', 'programa',
       'anio_pdl', 'socios', 'id_seccion', 'tipo'],
      dtype='object')

In [988]:
data_aca_2024 = data_aca_2024.drop(['id_seccion', 'tipo'], axis=1)

In [989]:
data_aca_2023 = data_aca_2023[['periodo', 'id_participante', 'grado', 'participante', 'ruralidad', 'curso', 'nivel_de_logro']]
data_aca_2024 = data_aca_2024[['periodo', 'id_participante', 'grado', 'participante', 'ruralidad', 'curso', 'nivel_de_logro']]

In [990]:
data_academico = pd.concat([data_aca_2023, data_aca_2024], ignore_index=True)
data_academico.shape

(44052, 7)

In [991]:
data_academico = data_academico.loc[~data_academico['grado'].isin(['Ini-5nto', 'Ini-4rto', 'Ini-3ero'])]

In [992]:
data_academico['id_part_grado'] = data_academico[['id_participante', 'grado']].astype(str).agg('-'.join, axis=1)
data_academico.drop(['id_participante','grado'], axis = 1, inplace=True)
data_academico.head()

,periodo,participante,ruralidad,curso,nivel_de_logro,id_part_grado
0,Diciembre 2023,"CHECA JIBAJA, JAEL",Rural,Matemática,En proceso,017311cc-Pri-6xto
1,Diciembre 2023,"CHECA JIBAJA, JAEL",Rural,Matemática,En inicio,017311cc-Pri-6xto
2,Diciembre 2023,"CHECA JIBAJA, JAEL",Rural,Matemática,En proceso,017311cc-Pri-6xto
3,Marzo 2023,"CCALACHUA CHICAniA, KATY RAYMUNDA",Rural,Matemática,Satisfactorio,b29b3dc9-Pri-1ero
4,Julio 2023,"CCALACHUA CHICAniA, KATY RAYMUNDA",Rural,Comunicación,Satisfactorio,b29b3dc9-Pri-2ndo

In [993]:
data_academico.nivel_de_logro.value_counts()

nivel_de_logro
En proceso       15598
Satisfactorio    14300
En inicio        12888
Name: count, dtype: int64

In [994]:
# Custom function to calculate mode
def calculate_mode(series):
    mode = series.mode()
    if not mode.empty:
        return mode.iloc[0]  # Return the first mode if there are multiple
    return np.nan  # Return NaN if no mode exists

In [995]:
# Pivot the table
# Convert 'nivel_de_logro' column to numeric, coercing errors to NaN
#data_qm['nivel_de_logro'] = pd.to_numeric(data_qm['puntaje'], errors='coerce')
data_academico = data_academico.pivot_table(
    index = ['periodo', 'id_part_grado', 'participante', 'ruralidad'],  # Group by participant and period
    columns ='curso',       # Use 'habilidad' as new columns
    values ='nivel_de_logro',                     # Use 'puntaje' as values
    aggfunc = calculate_mode                         # Use the custom mode function
).reset_index()  # Reset index to flatten the DataFrame

# Rename columns to remove the multi-index
data_academico.columns.name = None

data_academico.head()

,periodo,id_part_grado,participante,ruralidad,Ciencia y Tecnología,Comunicación,Inglés,Matemática
0,Diciembre 2023,017196bd-Pri-3ero,"BOniON MENDOZA, TEODOCIA",Urbana,NaN,Satisfactorio,En inicio,En proceso
1,Diciembre 2023,0172b301-Pri-6xto,"YUPANQUI QUISPE, ANDREA INÉS",Rural,NaN,En proceso,NaN,Satisfactorio
2,Diciembre 2023,0172b3c6-Pri-2ndo,"REQUEJO GOICOCHEA, OSCAR GIANCARLO",Rural,NaN,Satisfactorio,NaN,Satisfactorio
3,Diciembre 2023,0172b653-Pri-6xto,"RAMOS ESTRADA, AMILTHON",Rural,NaN,En proceso,NaN,Satisfactorio
4,Diciembre 2023,0172b72d-Sec-1ero,"TRIGOSO SANTILLAN, PERCY ALY",Urbana,NaN,NaN,Satisfactorio,NaN

In [996]:
(data_academico.isnull().sum()/data_academico.shape[0])*100

periodo                  0.000000
id_part_grado            0.000000
participante             0.000000
ruralidad                0.000000
Ciencia y Tecnología    85.818561
Comunicación            42.022941
Inglés                  76.955162
Matemática              49.217935
dtype: float64

In [997]:
data_academico.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 959 entries, 0 to 958
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   periodo               959 non-null    object
 1   id_part_grado         959 non-null    object
 2   participante          959 non-null    object
 3   ruralidad             959 non-null    object
 4   Ciencia y Tecnología  136 non-null    object
 5   Comunicación          556 non-null    object
 6   Inglés                221 non-null    object
 7   Matemática            487 non-null    object
dtypes: object(8)
memory usage: 60.1+ KB

## Socioemocional

In [998]:
data_soc_2023 = pd.read_csv('../data/socioemocional_2023.csv', encoding='latin1', sep = ';')
data_soc_2024 = pd.read_csv('../data/socioemocional_2024.csv', encoding='latin1', sep = ';')

In [999]:
data_soc_2023.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144730 entries, 0 to 144729
Data columns (total 24 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   anio                   144730 non-null  int64
 1   region_ie              144730 non-null  object
 2   provincia_ie           144730 non-null  object
 3   ugel_ie                144730 non-null  object
 4   distrito_ie            144730 non-null  object
 5   centropoblado_ie       144730 non-null  object
 6   institucion_educativa  144730 non-null  object
 7   codigolocal_ie         144730 non-null  int64
 8   codigomodular_ie       144730 non-null  int64
 9   ruralidad              144730 non-null  object
 10  id_estudiante          144730 non-null  object
 11  grado                  144730 non-null  object
 12  fecha                  144730 non-null  object
 13  evaluación             144730 non-null  object
 14  habilidad              144730 non-null  object
 15  promedio               144730 non-null  float64
 16  nivel_de_logro         144730 non-null  object
 17  dni_participante       144692 non-null  object
 18  id_participante        144730 non-null  object
 19  participantes_sección  144730 non-null  object
 20  coordinador_a          144730 non-null  object
 21  programa               144730 non-null  object
 22  anio_pdl               144730 non-null  object
 23  socios                 144730 non-null  object
dtypes: float64(1), int64(3), object(20)
memory usage: 26.5+ MB

In [1000]:
data_soc_2024.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 199093 entries, 0 to 199092
Data columns (total 25 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   anio                   199093 non-null  int64
 1   region_ie              199093 non-null  object
 2   provincia_ie           199093 non-null  object
 3   ugel_ie                199093 non-null  object
 4   distrito_ie            199093 non-null  object
 5   centropoblado_ie       199093 non-null  object
 6   institucion_educativa  199093 non-null  object
 7   codigolocal_ie         199093 non-null  int64
 8   codigomodular_ie       199093 non-null  int64
 9   ruralidad              199093 non-null  object
 10  id_estudiante          199093 non-null  object
 11  grado                  199093 non-null  object
 12  fecha                  199093 non-null  object
 13  evaluación             199093 non-null  object
 14  habilidad              199093 non-null  object
 15  promedio               199093 non-null  float64
 16  nivel_de_logro         199093 non-null  object
 17  dni_participante       199093 non-null  int64
 18  id_participante        199093 non-null  object
 19  participantes_sección  199093 non-null  object
 20  coordinador_a          199093 non-null  object
 21  programa               199093 non-null  object
 22  anio_pdl               199093 non-null  object
 23  socios                 198789 non-null  object
 24  id_seccion             199093 non-null  object
dtypes: float64(1), int64(4), object(20)
memory usage: 38.0+ MB

In [1001]:
data_soc_2023.programa.value_counts()

programa
PDL    104499
QM      40231
Name: count, dtype: int64

In [1002]:
data_soc_2024.programa.value_counts()

programa
QM     102149
PDL     96944
Name: count, dtype: int64

In [1003]:
data_soc_2024['evaluación'].unique()

array(['Habilidades Socioemocionales', 'Factores de riesgo'], dtype=object)

In [1004]:
data_soc_2023 = data_soc_2023.loc[data_soc_2023.programa == 'PDL']
data_soc_2024 = data_soc_2024.loc[data_soc_2024.programa == 'PDL']

In [1005]:
data_soc_2023 = data_soc_2023.loc[data_soc_2023['evaluación'] == 'Habilidades Socioemocionales']
data_soc_2024 = data_soc_2024.loc[data_soc_2024['evaluación'] == 'Habilidades Socioemocionales']

In [1006]:
data_soc_2023.nivel_de_logro.value_counts()

nivel_de_logro
Satisfactorio    42775
En proceso       22661
En inicio         5544
Name: count, dtype: int64

In [1007]:
data_soc_2024.nivel_de_logro.value_counts()

nivel_de_logro
Satisfactorio      42736
En proceso         18742
En inicio           3878
Riesgo moderado      761
Alto riesgo          294
Bajo Riesgo          286
Name: count, dtype: int64

In [1008]:
data_soc_2023.columns

Index(['anio', 'region_ie', 'provincia_ie', 'ugel_ie', 'distrito_ie',
       'centropoblado_ie', 'institucion_educativa', 'codigolocal_ie',
       'codigomodular_ie', 'ruralidad', 'id_estudiante', 'grado', 'fecha',
       'evaluación', 'habilidad', 'promedio', 'nivel_de_logro',
       'dni_participante', 'id_participante', 'participantes_sección',
       'coordinador_a', 'programa', 'anio_pdl', 'socios'],
      dtype='object')

In [1009]:
data_soc_2023.nivel_de_logro.unique()

array(['Satisfactorio', 'En proceso', 'En inicio'], dtype=object)

In [1010]:
data_soc_2024.columns

Index(['anio', 'region_ie', 'provincia_ie', 'ugel_ie', 'distrito_ie',
       'centropoblado_ie', 'institucion_educativa', 'codigolocal_ie',
       'codigomodular_ie', 'ruralidad', 'id_estudiante', 'grado', 'fecha',
       'evaluación', 'habilidad', 'promedio', 'nivel_de_logro',
       'dni_participante', 'id_participante', 'participantes_sección',
       'coordinador_a', 'programa', 'anio_pdl', 'socios', 'id_seccion'],
      dtype='object')

In [1011]:
sorted(data_soc_2023.habilidad.unique())

['Autoconcepto',
 'Autocuidado',
 'Autoestima',
 'Comportamiento prosocial',
 'Comunicación asertiva',
 'Conciencia emocional',
 'Conciencia social',
 'Creatividad',
 'Empatía',
 'Percepción sobre estereotipos de género',
 'Regulación emocional',
 'Resolución de conflictos',
 'Toma de decisiones responsables',
 'Trabajo en equipo']

In [1012]:
sorted(data_soc_2024.habilidad.unique())

['Autoconcepto',
 'Autocuidado',
 'Autoestima',
 'Comportamiento prosocial',
 'Comunicación asertiva',
 'Conciencia emocional',
 'Conciencia social',
 'Creatividad',
 'Empatía',
 'Percepción sobre Estereotipos de género',
 'Regulación emocional',
 'Resolución de conflictos',
 'Toma de decisiones responsables',
 'Trabajo en equipo']

In [1013]:
data_soc_2024.loc[data_soc_2024['habilidad'] == 'Percepción sobre Estereotipos de género', 'habilidad'] = 'Percepción sobre estereotipos de género'

In [1014]:
data_soc_2024 = data_soc_2024.loc[~(data_soc_2024.habilidad == "Desinformación sobre educación sexual reproductiva")]

In [1015]:
data_soc_2024 = data_soc_2024.drop(['id_seccion'], axis=1)

In [1016]:
data_soc_2023.nivel_de_logro.unique()

array(['Satisfactorio', 'En proceso', 'En inicio'], dtype=object)

### ¿Que significado tiene la columna Promedio?

In [1017]:
def check_dist(data_academico):
    data = data_academico.copy()
    for u_val in data.nivel_de_logro.unique():
        min_ = data.loc[data.nivel_de_logro == u_val].promedio.min()
        max_ = data.loc[data.nivel_de_logro == u_val].promedio.max()
        mean_ = data.loc[data.nivel_de_logro == u_val].promedio.mean()
        print(f'{u_val}: min = {min_}, max = {max_}, mean = {mean_}')

In [1018]:
check_dist(data_soc_2023)

Satisfactorio: min = 0.833333333, max = 4.0, mean = 2.590954607430485
En proceso: min = 0.333333333, max = 2.75, mean = 1.6503390553967612
En inicio: min = 0.0, max = 1.0, mean = 0.20795755170905486

In [1019]:
check_dist(data_soc_2024)

Satisfactorio: min = 1.0, max = 8.0, mean = 2.5481918704913653
En proceso: min = 0.333333333, max = 3.333333333, mean = 1.666444349628695
Bajo Riesgo: min = 1.0, max = 1.0, mean = 1.0
En inicio: min = 0.0, max = 2.5, mean = 0.13119950146132028
Alto riesgo: min = 3.0, max = 4.0, mean = 3.3704648526020407
Riesgo moderado: min = 1.25, max = 2.75, mean = 2.017247043365309

In [1020]:
data_soc_2023 = data_soc_2023.rename(columns={'fecha': 'periodo'})

In [1021]:
data_soc_2024 = data_soc_2024.rename(columns={'fecha': 'periodo'})

In [1022]:
data_soc_2023 = data_soc_2023.rename(columns={'participantes_sección': 'participante'})
data_soc_2024 = data_soc_2024.rename(columns={'participantes_sección': 'participante'})

In [1023]:
data_soc_2023 = data_soc_2023[['periodo', 'id_participante', 'grado', 'participante', 'ruralidad', 'habilidad', 'nivel_de_logro']]
data_soc_2024 = data_soc_2024[['periodo', 'id_participante', 'grado', 'participante', 'ruralidad', 'habilidad', 'nivel_de_logro']]

In [1024]:
data_socioemocional = pd.concat([data_soc_2023, data_soc_2024], ignore_index=True)
data_socioemocional.shape

(137677, 7)

In [1025]:
data_socioemocional['id_part_grado'] = data_socioemocional[['id_participante', 'grado']].astype(str).agg('-'.join, axis=1)
data_socioemocional.drop(['id_participante','grado'], axis = 1, inplace=True)
data_socioemocional.head()

,periodo,participante,ruralidad,habilidad,nivel_de_logro,id_part_grado
0,Diciembre 2023,"ALANYA HARTLEY, SEBASTIAN",Urbana,Autoconcepto,Satisfactorio,0173d57a-Sec-4rto
1,Diciembre 2023,"ALANYA HARTLEY, SEBASTIAN",Urbana,Autocuidado,Satisfactorio,0173d57a-Sec-4rto
2,Diciembre 2023,"ALANYA HARTLEY, SEBASTIAN",Urbana,Autoestima,Satisfactorio,0173d57a-Sec-4rto
3,Diciembre 2023,"ALANYA HARTLEY, SEBASTIAN",Urbana,Comportamiento prosocial,En proceso,0173d57a-Sec-4rto
4,Diciembre 2023,"ALANYA HARTLEY, SEBASTIAN",Urbana,Comunicación asertiva,Satisfactorio,0173d57a-Sec-4rto

In [1026]:
data_socioemocional.id_part_grado.nunique()

389

In [1027]:
# Pivot the table
# Convert 'nivel_de_logro' column to numeric, coercing errors to NaN
#data_qm['nivel_de_logro'] = pd.to_numeric(data_qm['puntaje'], errors='coerce')
data_socioemocional = data_socioemocional.pivot_table(
    index = ['periodo', 'id_part_grado', 'participante', 'ruralidad'],  # Group by participant and period
    columns ='habilidad',       # Use 'habilidad' as new columns
    values ='nivel_de_logro',                     # Use 'puntaje' as values
    aggfunc = calculate_mode                         # Use the custom mode function
).reset_index()  # Reset index to flatten the DataFrame

# Rename columns to remove the multi-index
data_socioemocional.columns.name = None

data_socioemocional.head()

,periodo,id_part_grado,participante,ruralidad,Autoconcepto,Autocuidado,Autoestima,Comportamiento prosocial,Comunicación asertiva,Conciencia emocional,Conciencia social,Creatividad,Empatía,Percepción sobre estereotipos de género,Regulación emocional,Resolución de conflictos,Toma de decisiones responsables,Trabajo en equipo
0,Diciembre 2023,017196bd-Pri-3ero,"BOniON MENDOZA, TEODOCIA",Urbana,NaN,Satisfactorio,Satisfactorio,NaN,NaN,Satisfactorio,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Diciembre 2023,0172b301-Pri-6xto,"YUPANQUI QUISPE, ANDREA INÉS",Rural,Satisfactorio,Satisfactorio,Satisfactorio,En proceso,Satisfactorio,NaN,Satisfactorio,NaN,Satisfactorio,NaN,En proceso,Satisfactorio,En proceso,Satisfactorio
2,Diciembre 2023,0172b3c6-Pri-2ndo,"REQUEJO GOICOCHEA, OSCAR GIANCARLO",Rural,NaN,Satisfactorio,Satisfactorio,NaN,NaN,En proceso,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Diciembre 2023,0172b653-Pri-6xto,"RAMOS ESTRADA, AMILTHON",Rural,Satisfactorio,Satisfactorio,Satisfactorio,En proceso,En proceso,NaN,Satisfactorio,NaN,Satisfactorio,NaN,Satisfactorio,Satisfactorio,En proceso,En proceso
4,Diciembre 2023,0172b72d-Sec-1ero,"TRIGOSO SANTILLAN, PERCY ALY",Urbana,Satisfactorio,Satisfactorio,En proceso,Satisfactorio,Satisfactorio,Satisfactorio,En proceso,Satisfactorio,Satisfactorio,En inicio,Satisfactorio,Satisfactorio,Satisfactorio,En proceso

In [1028]:
data_socioemocional.shape

(970, 18)

## Clima de Aula

In [1029]:
data_clima_2023 = pd.read_csv('../data/clima_aula_2023.csv', encoding='latin1', sep = ';')
data_clima_2024 = pd.read_csv('../data/clima_aula_2024.csv', encoding='latin1', sep = ';')

In [1030]:
data_clima_2023.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7719 entries, 0 to 7718
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   anio                   7719 non-null   int64
 1   region_ie              7719 non-null   object
 2   provincia_ie           7719 non-null   object
 3   ugel_ie                7719 non-null   object
 4   distrito_ie            7719 non-null   object
 5   centropoblado_ie       7719 non-null   object
 6   institucion_educativa  7719 non-null   object
 7   codigolocal_ie         7719 non-null   int64
 8   codigomodular_ie       7719 non-null   int64
 9   ruralidad              7719 non-null   object
 10  grado                  7719 non-null   object
 11  periodo                7719 non-null   object
 12  evaluacion             7719 non-null   object
 13  elemento               7719 non-null   object
 14  porcentaje_positivas   7694 non-null   object
 15  nivel_de_logro         7719 non-null   object
 16  dni_participante       7705 non-null   object
 17  id_participante        7719 non-null   object
 18  participante           7719 non-null   object
 19  coordinador_a          7719 non-null   object
 20  programa               7719 non-null   object
 21  anio_pdl               7719 non-null   object
 22  socios                 7719 non-null   object
dtypes: int64(3), object(20)
memory usage: 1.4+ MB

In [1031]:
data_clima_2024.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5481 entries, 0 to 5480
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   anio                   5481 non-null   int64
 1   region_ie              5481 non-null   object
 2   provincia_ie           5481 non-null   object
 3   ugel_ie                5481 non-null   object
 4   distrito_ie            5481 non-null   object
 5   centropoblado_ie       5481 non-null   object
 6   institucion_educativa  5481 non-null   object
 7   codigolocal_ie         5481 non-null   int64
 8   codigomodular_ie       5481 non-null   int64
 9   ruralidad              5481 non-null   object
 10  grado                  5481 non-null   object
 11  periodo                5481 non-null   object
 12  evaluacion             5481 non-null   object
 13  elemento               5481 non-null   object
 14  porcentaje__positivas  5481 non-null   object
 15  nivel_de_logro         5481 non-null   object
 16  dni_participante       5481 non-null   int64
 17  id_participante        5481 non-null   object
 18  participante           5481 non-null   object
 19  coordinador_a          5481 non-null   object
 20  programa               5481 non-null   object
 21  anio_pdl               5481 non-null   object
 22  socios                 5460 non-null   object
 23  id_seccion             5481 non-null   object
dtypes: int64(4), object(20)
memory usage: 1.0+ MB

In [1032]:
data_clima_2023.nivel_de_logro.value_counts()

nivel_de_logro
Satisfactorio    3921
En proceso       3217
En inicio         581
Name: count, dtype: int64

In [1033]:
data_clima_2024.nivel_de_logro.value_counts()

nivel_de_logro
En proceso       2754
En inicio        2214
Satisfactorio     513
Name: count, dtype: int64

In [1034]:
data_clima_2023 = data_clima_2023.loc[data_clima_2023.programa == 'PDL']
data_clima_2024 = data_clima_2024.loc[data_clima_2024.programa == 'PDL']

In [1035]:
data_clima_2023.columns

Index(['anio', 'region_ie', 'provincia_ie', 'ugel_ie', 'distrito_ie',
       'centropoblado_ie', 'institucion_educativa', 'codigolocal_ie',
       'codigomodular_ie', 'ruralidad', 'grado', 'periodo', 'evaluacion',
       'elemento', 'porcentaje_positivas', 'nivel_de_logro',
       'dni_participante', 'id_participante', 'participante', 'coordinador_a',
       'programa', 'anio_pdl', 'socios'],
      dtype='object')

In [1036]:
data_clima_2024.columns

Index(['anio', 'region_ie', 'provincia_ie', 'ugel_ie', 'distrito_ie',
       'centropoblado_ie', 'institucion_educativa', 'codigolocal_ie',
       'codigomodular_ie', 'ruralidad', 'grado', 'periodo', 'evaluacion',
       'elemento', 'porcentaje__positivas', 'nivel_de_logro',
       'dni_participante', 'id_participante', 'participante', 'coordinador_a',
       'programa', 'anio_pdl', 'socios', 'id_seccion'],
      dtype='object')

In [1037]:
sorted(data_clima_2023.elemento.unique())

['Aprendizaje completamente interiorizado',
 'Comprensión comprobada y asegurada',
 'Expectativas rigurosas mantenidas',
 'Se crea una cultura positiva y un entorno de aprendizaje.',
 'Se establece un entorno de aprendizaje atractivo',
 'Se fomentan relaciones alentadoras y de apoyo.',
 'Se valoran los aportes y las ideas de los estudiantes']

In [1038]:
sorted(data_clima_2024.elemento.unique())

['Aprendizaje completamente interiorizado',
 'Comprensión comprobada y asegurada',
 'Expectativas rigurosas mantenidas',
 'Se crea una cultura positiva y un entorno de aprendizaje',
 'Se establece un entorno de aprendizaje atractivo',
 'Se fomentan relaciones alentadoras y de apoyo',
 'Se valoran los aportes y las ideas de los estudiantes']

In [1039]:
data_clima_2023.loc[data_clima_2023['elemento'] == 'Se crea una cultura positiva y un entorno de aprendizaje.', 'elemento'] = 'Se crea una cultura positiva y un entorno de aprendizaje'

In [1040]:
data_clima_2023.loc[data_clima_2023['elemento'] == 'Se fomentan relaciones alentadoras y de apoyo.', 'elemento'] = 'Se fomentan relaciones alentadoras y de apoyo'

In [1041]:
data_clima_2024 = data_clima_2024.rename(columns={'porcentaje__positivas': 'porcentaje_positivas'})

In [1042]:
data_clima_2024 = data_clima_2024.drop(['id_seccion'], axis=1)

In [1043]:
data_clima_2023 = data_clima_2023[['periodo', 'id_participante', 'grado', 'participante', 'ruralidad', 'elemento', 'nivel_de_logro']]
data_clima_2024 = data_clima_2024[['periodo', 'id_participante', 'grado', 'participante', 'ruralidad', 'elemento', 'nivel_de_logro']]

In [1044]:
data_clima_aula = pd.concat([data_clima_2023, data_clima_2024], ignore_index=True)
data_clima_aula.shape

(8188, 7)

In [1045]:
data_clima_aula['id_part_grado'] = data_clima_aula[['id_participante', 'grado']].astype(str).agg('-'.join, axis=1)
data_clima_aula.drop(['id_participante','grado'], axis = 1, inplace=True)
data_clima_aula.head()

,periodo,participante,ruralidad,elemento,nivel_de_logro,id_part_grado
0,Marzo 2023,"CHANA CHANA, EVA",Rural,Aprendizaje completamente interiorizado,Satisfactorio,b29b10f0-Pri-6xto
1,Julio 2023,"RAMIREZ RAMIREZ, MILAGROS",Rural,Expectativas rigurosas mantenidas,Satisfactorio,b29b536b-Pri-5nto
2,Diciembre 2023,"ZAPATA LIZANA, ADA DEL ROSARIO",Rural,Aprendizaje completamente interiorizado,Satisfactorio,4b581147-Pri-1ero
3,Diciembre 2023,"ZAPATA LIZANA, ADA DEL ROSARIO",Rural,Comprensión comprobada y asegurada,Satisfactorio,4b581147-Pri-1ero
4,Julio 2023,"UTURUNCO UTURUNCO, WILLIAN",Rural,Se establece un entorno de aprendizaje atractivo,En proceso,b29b30b1-Pri-4rto

In [1046]:
data_clima_aula.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8188 entries, 0 to 8187
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   periodo         8188 non-null   object
 1   participante    8188 non-null   object
 2   ruralidad       8188 non-null   object
 3   elemento        8188 non-null   object
 4   nivel_de_logro  8188 non-null   object
 5   id_part_grado   8188 non-null   object
dtypes: object(6)
memory usage: 383.9+ KB

In [1047]:
data_clima_aula.id_part_grado.nunique()

427

In [1048]:
# Pivot the table
# Convert 'nivel_de_logro' column to numeric, coercing errors to NaN
#data_qm['nivel_de_logro'] = pd.to_numeric(data_qm['puntaje'], errors='coerce')
data_clima_aula = data_clima_aula.pivot_table(
    index = ['periodo', 'id_part_grado', 'participante', 'ruralidad'],  # Group by participant and period
    columns ='elemento',       # Use 'habilidad' as new columns
    values ='nivel_de_logro',                     # Use 'puntaje' as values
    aggfunc = calculate_mode                         # Use the custom mode function
).reset_index()  # Reset index to flatten the DataFrame

# Rename columns to remove the multi-index
data_clima_aula.columns.name = None

data_clima_aula.head()

,periodo,id_part_grado,participante,ruralidad,Aprendizaje completamente interiorizado,Comprensión comprobada y asegurada,Expectativas rigurosas mantenidas,Se crea una cultura positiva y un entorno de aprendizaje,Se establece un entorno de aprendizaje atractivo,Se fomentan relaciones alentadoras y de apoyo,Se valoran los aportes y las ideas de los estudiantes
0,Diciembre 2023,017196bd-Pri-3ero,"BOniON MENDOZA, TEODOCIA",Urbana,Satisfactorio,Satisfactorio,En proceso,En proceso,Satisfactorio,Satisfactorio,Satisfactorio
1,Diciembre 2023,0172b301-Pri-6xto,"YUPANQUI QUISPE, ANDREA INÉS",Rural,Satisfactorio,Satisfactorio,En inicio,En proceso,Satisfactorio,Satisfactorio,Satisfactorio
2,Diciembre 2023,0172b3c6-Pri-2ndo,"REQUEJO GOICOCHEA, OSCAR GIANCARLO",Rural,Satisfactorio,Satisfactorio,Satisfactorio,Satisfactorio,Satisfactorio,Satisfactorio,Satisfactorio
3,Diciembre 2023,0172b653-Pri-6xto,"RAMOS ESTRADA, AMILTHON",Rural,Satisfactorio,Satisfactorio,En inicio,En proceso,Satisfactorio,Satisfactorio,Satisfactorio
4,Diciembre 2023,0172b72d-Sec-1ero,"TRIGOSO SANTILLAN, PERCY ALY",Urbana,Satisfactorio,Satisfactorio,Satisfactorio,En inicio,En proceso,Satisfactorio,Satisfactorio

In [1049]:
data_clima_aula.shape

(1105, 11)

## Limpieza de datos

In [1050]:
data_academico.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 959 entries, 0 to 958
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   periodo               959 non-null    object
 1   id_part_grado         959 non-null    object
 2   participante          959 non-null    object
 3   ruralidad             959 non-null    object
 4   Ciencia y Tecnología  136 non-null    object
 5   Comunicación          556 non-null    object
 6   Inglés                221 non-null    object
 7   Matemática            487 non-null    object
dtypes: object(8)
memory usage: 60.1+ KB

In [1051]:
data_socioemocional.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 970 entries, 0 to 969
Data columns (total 18 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   periodo                                  970 non-null    object
 1   id_part_grado                            970 non-null    object
 2   participante                             970 non-null    object
 3   ruralidad                                970 non-null    object
 4   Autoconcepto                             652 non-null    object
 5   Autocuidado                              970 non-null    object
 6   Autoestima                               965 non-null    object
 7   Comportamiento prosocial                 647 non-null    object
 8   Comunicación asertiva                    648 non-null    object
 9   Conciencia emocional                     723 non-null    object
 10  Conciencia social                        647 non-null    object
 11  Creatividad                              402 non-null    object
 12  Empatía                                  648 non-null    object
 13  Percepción sobre estereotipos de género  177 non-null    object
 14  Regulación emocional                     648 non-null    object
 15  Resolución de conflictos                 648 non-null    object
 16  Toma de decisiones responsables          648 non-null    object
 17  Trabajo en equipo                        648 non-null    object
dtypes: object(18)
memory usage: 136.5+ KB

In [1052]:
data_clima_aula.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1105 entries, 0 to 1104
Data columns (total 11 columns):
 #   Column                                                    Non-Null Count  Dtype
---  ------                                                    --------------  -----
 0   periodo                                                   1105 non-null   object
 1   id_part_grado                                             1105 non-null   object
 2   participante                                              1105 non-null   object
 3   ruralidad                                                 1105 non-null   object
 4   Aprendizaje completamente interiorizado                   1105 non-null   object
 5   Comprensión comprobada y asegurada                        1105 non-null   object
 6   Expectativas rigurosas mantenidas                         1105 non-null   object
 7   Se crea una cultura positiva y un entorno de aprendizaje  1105 non-null   object
 8   Se establece un entorno de aprendizaje atractivo          1105 non-null   object
 9   Se fomentan relaciones alentadoras y de apoyo             1105 non-null   object
 10  Se valoran los aportes y las ideas de los estudiantes     1105 non-null   object
dtypes: object(11)
memory usage: 95.1+ KB

In [1053]:
null_percentage = data_academico.isnull().mean()
# Filter columns with more than 70% null values
columns_to_drop = null_percentage[null_percentage > 0.7].index

# Drop the columns
data_academico = data_academico.drop(columns=columns_to_drop)

In [1054]:
null_percentage = data_socioemocional.isnull().mean()
# Filter columns with more than 70% null values
columns_to_drop = null_percentage[null_percentage > 0.7].index

# Drop the columns
data_socioemocional = data_socioemocional.drop(columns=columns_to_drop)

In [1055]:
null_percentage = data_clima_aula.isnull().mean()
# Filter columns with more than 70% null values
columns_to_drop = null_percentage[null_percentage > 0.7].index

# Drop the columns
data_clima_aula = data_clima_aula.drop(columns=columns_to_drop)

In [1056]:
data_academico.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 959 entries, 0 to 958
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   periodo        959 non-null    object
 1   id_part_grado  959 non-null    object
 2   participante   959 non-null    object
 3   ruralidad      959 non-null    object
 4   Comunicación   556 non-null    object
 5   Matemática     487 non-null    object
dtypes: object(6)
memory usage: 45.1+ KB

In [1057]:
data_socioemocional.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 970 entries, 0 to 969
Data columns (total 17 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   periodo                          970 non-null    object
 1   id_part_grado                    970 non-null    object
 2   participante                     970 non-null    object
 3   ruralidad                        970 non-null    object
 4   Autoconcepto                     652 non-null    object
 5   Autocuidado                      970 non-null    object
 6   Autoestima                       965 non-null    object
 7   Comportamiento prosocial         647 non-null    object
 8   Comunicación asertiva            648 non-null    object
 9   Conciencia emocional             723 non-null    object
 10  Conciencia social                647 non-null    object
 11  Creatividad                      402 non-null    object
 12  Empatía                          648 non-null    object
 13  Regulación emocional             648 non-null    object
 14  Resolución de conflictos         648 non-null    object
 15  Toma de decisiones responsables  648 non-null    object
 16  Trabajo en equipo                648 non-null    object
dtypes: object(17)
memory usage: 129.0+ KB

In [1058]:
data_clima_aula.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1105 entries, 0 to 1104
Data columns (total 11 columns):
 #   Column                                                    Non-Null Count  Dtype
---  ------                                                    --------------  -----
 0   periodo                                                   1105 non-null   object
 1   id_part_grado                                             1105 non-null   object
 2   participante                                              1105 non-null   object
 3   ruralidad                                                 1105 non-null   object
 4   Aprendizaje completamente interiorizado                   1105 non-null   object
 5   Comprensión comprobada y asegurada                        1105 non-null   object
 6   Expectativas rigurosas mantenidas                         1105 non-null   object
 7   Se crea una cultura positiva y un entorno de aprendizaje  1105 non-null   object
 8   Se establece un entorno de aprendizaje atractivo          1105 non-null   object
 9   Se fomentan relaciones alentadoras y de apoyo             1105 non-null   object
 10  Se valoran los aportes y las ideas de los estudiantes     1105 non-null   object
dtypes: object(11)
memory usage: 95.1+ KB

In [1059]:
data_academico.id_part_grado.nunique()

370

In [1060]:
data_socioemocional.id_part_grado.nunique()

389

In [1061]:
data_clima_aula.id_part_grado.nunique()

427

In [1062]:
# Step 1: Replace categorical values with numeric values
replace_dict = {
    'En inicio': 1,
    'En proceso': 2,
    'Satisfactorio': 3
}

data_academico['Comunicación'] = data_academico['Comunicación'].replace(replace_dict).astype(float)
data_academico['Matemática'] = data_academico['Matemática'].replace(replace_dict).astype(float)



# Step 3: Group by id_part_grado and periodo
grouped = data_academico.groupby(['id_part_grado', 'periodo'])

# Step 4: Calculate the mean of Comunicación and Matemática for each row within the group
data_academico['nivel_de_logro_aca'] = grouped.apply(lambda x: x[['Comunicación', 'Matemática']].mean(axis=1), include_groups=False).reset_index(level=[0, 1], drop=True)

# Step 5: Create new columns indicating whether Comunicación and Matemática have values
data_academico['Comunicación'] = data_academico['Comunicación'].notna().astype(int)
data_academico['Matemática'] = data_academico['Matemática'].notna().astype(int)

# Step 2: Replace nulls with 0 in Comunicación and Matemática
data_academico['Comunicación'] = data_academico['Comunicación'].fillna(0)
data_academico['Matemática'] = data_academico['Matemática'].fillna(0)

C:\Users\jange\AppData\Local\Temp\ipykernel_65780\1057685536.py:8: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data_academico['Comunicación'] = data_academico['Comunicación'].replace(replace_dict).astype(float)
C:\Users\jange\AppData\Local\Temp\ipykernel_65780\1057685536.py:9: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data_academico['Matemática'] = data_academico['Matemática'].replace(replace_dict).astype(float)

In [1063]:
data_academico.sample(40)

,periodo,id_part_grado,participante,ruralidad,Comunicación,Matemática,nivel_de_logro_aca
820,Marzo 2023,b29b65cd-Pri-6xto,"ZAPATA SOSA, LUIS JUNIOR",Urbana,1,1,2.0
732,Marzo 2023,b29b1c8f-Pri-1ero,"CALSINA CCAMA, YULEYSI KAROL",Rural,1,1,3.0
728,Marzo 2023,b29b156b-Pri-4rto,"JURADO MANDUJANO, VANESSA FABIOLA",Rural,1,1,1.5
583,Julio 2024,b29b410a2024-Pri-5nto,"PANTA ROBLEDO, CAROL NICOL",Rural,1,0,3.0
907,Marzo 2024,b29b3c342024-Sec-5nto,"LANCHIPA VILDOSO, GIANELLA MILAGROS",Rural,1,0,1.0
43,Diciembre 2023,0172d1a3-Pri-5nto,"MARMOLEJO CABRERA, ALEXANDRA KARINA",Urbana,1,1,2.5
367,Julio 2023,0173cec7-Pri-4rto,"POZO OSORIO, SWANNE MARIELLE",Rural,0,0,NaN
252,Diciembre 2024,b29b2d4b2024-Sec-1ero,"YLLA QUENAYA, CARLOS JAVIER",Urbana,1,0,2.0
391,Julio 2023,4b581318-Pri-4rto,"VASQUEZ PLASENCIA, JOSELYN MERLY",Urbana,1,1,1.5
131,Diciembre 2023,b29b35f6-Sec-1ero,"BOZA CCOYLLAR, BRANDO",Rural,0,1,1.0
672,Marzo 2023,0173cb97-Pri-6xto,"VILCHEZ MARTINEZ, HELDER JOSE",Rural,1,1,1.5
695,Marzo 2023,0fc63051-Pri-5nto,"PAUCAR CERNA, ROXANA VIRGINIA",Urbana,0,0,NaN
190,Diciembre 2023,b29b617a-Sec-1ero,"BENITO PILCO, GLADYS",Rural,1,0,3.0
950,Marzo 2024,b29b676c2024-Sec-4rto,"CHAVEZ APAZA, ELIZABETH",Rural,0,1,2.0
901,Marzo 2024,b29b38122024-Pri-5nto,"CÉLIZ VÁSQUEZ, GABRIELA",Urbana,0,0,NaN
697,Marzo 2023,114cff83-Pri-1ero,"COLONIA LIZANO, MARYORI JOMIRA",Rural,1,1,3.0
461,Julio 2023,b29b4931-Pri-1ero,"VARGAS REBOLLEDO, VALERIA ESTEFANIA",Rural,1,1,3.0
101,Diciembre 2023,b29b0eb1-Pri-3ero,"CHUSHO NUniEZ, MILAGROS VIVIANA",Urbana,0,0,NaN
630,Marzo 2023,0172b861-Pri-1ero,"TORRES HUAMANI, RUDDY ESTEFANI",Rural,1,1,3.0
680,Marzo 2023,0173cec7-Pri-5nto,"POZO OSORIO, SWANNE MARIELLE",Rural,0,0,NaN
735,Marzo 2023,b29b1ecc-Pri-5nto,"QUISPE APAZA, THAID LINDALVA",Rural,1,1,1.0
637,Marzo 2023,0172c1bf-Sec-1ero,"CCOYA ARAPA, JESUS ANGEL",Rural,0,1,1.0
917,Marzo 2024,b29b421e2024-Sec-4rto,"TEQUEN SANCHEZ, HUGO MARCO",Urbana,0,1,1.0
698,Marzo 2023,114cff83-Pri-2ndo,"COLONIA LIZANO, MARYORI JOMIRA",Rural,1,1,2.0
214,Diciembre 2024,649c6ebe85ed5a1e530a6e52-Sec-3ero,"JARAMILLO CORDOVA, ROSA GABRIELA",Rural,0,1,2.0
343,Julio 2023,0172cc42-Pri-4rto,"FERNANDEZ CONTRERAS, SHERLEY PAMELA",Urbana,0,0,NaN
20,Diciembre 2023,0172c380-Pri-2ndo,"BUITRON ZARRIA, KIARA DEL CARMEN",Rural,1,1,3.0
920,Marzo 2024,b29b47192024-Pri-4rto,"VILCAHUAMAN NOLI, GINA MILAGROS",Rural,0,0,NaN
881,Marzo 2024,b29b18ab2024-Sec-1ero,"SAENZ CHISQUIPAMA, MIGUEL ANGEL",Urbana,0,1,1.0
452,Julio 2023,b29b3f66-Pri-4rto,"CALIZAYA CALIZAYA, JENNY ALESSANDRA",Rural,1,0,3.0
257,Diciembre 2024,b29b35f62024-Sec-3ero,"BOZA CCOYLLAR, BRANDO",Rural,0,1,1.0
378,Julio 2023,0173d57a-Sec-5nto,"ALANYA HARTLEY, SEBASTIAN",Urbana,1,0,2.0
632,Marzo 2023,0172be90-Pri-3ero,"CALDERON VITE, LUISA ANDREA",Rural,1,1,1.0
437,Julio 2023,b29b3aaa-Sec-1ero,"HUANCAYA CARDENAS, LUZ KAREM",Rural,0,0,NaN
467,Julio 2023,b29b51c8-Pri-2ndo,"QUILLA MENDOZA, LYNN",Rural,1,0,3.0
89,Diciembre 2023,7126386b-Sec-3ero,"RAMIREZ LARREATEGUI, JAVIER",Rural,0,1,2.0
334,Julio 2023,0172c783-Pri-6xto,"GALVEZ CRUZ, JUAN RAMON",Rural,1,1,2.5
448,Julio 2023,b29b3dc9-Pri-2ndo,"CCALACHUA CHICAniA, KATY RAYMUNDA",Rural,1,1,3.0
152,Diciembre 2023,b29b3e4f-Pri-4rto,"LOBATON FLORES, CADY EYTABEL",Urbana,0,0,NaN
4,Diciembre 2023,0172b72d-Sec-1ero,"TRIGOSO SANTILLAN, PERCY ALY",Urbana,0,0,NaN

In [1064]:
data_socioemocional.sample(20)

,periodo,id_part_grado,participante,ruralidad,Autoconcepto,Autocuidado,Autoestima,Comportamiento prosocial,Comunicación asertiva,Conciencia emocional,Conciencia social,Creatividad,Empatía,Regulación emocional,Resolución de conflictos,Toma de decisiones responsables,Trabajo en equipo
603,Julio 2024,b29b584c2024-Pri-6xto,"GABINO MENDOZA, SHAMANTA DALLAM",Rural,Satisfactorio,Satisfactorio,Satisfactorio,En proceso,En proceso,NaN,Satisfactorio,NaN,Satisfactorio,En proceso,Satisfactorio,Satisfactorio,Satisfactorio
888,Marzo 2024,b29b301b2024-Pri-6xto,"MAYTA JIMENEZ, WENNIE",Urbana,Satisfactorio,Satisfactorio,Satisfactorio,En proceso,Satisfactorio,NaN,Satisfactorio,NaN,Satisfactorio,En proceso,Satisfactorio,Satisfactorio,En proceso
741,Marzo 2023,b29b2f00-Sec-2ndo,"MONTORO PADILLA, JASSIRRA IBANIA",Rural,En proceso,En proceso,Satisfactorio,Satisfactorio,En proceso,Satisfactorio,En proceso,En proceso,Satisfactorio,Satisfactorio,En proceso,Satisfactorio,Satisfactorio
90,Diciembre 2023,b29b156b-Pri-3ero,"JURADO MANDUJANO, VANESSA FABIOLA",Rural,NaN,Satisfactorio,En proceso,NaN,NaN,Satisfactorio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
474,Julio 2023,b29b6f91-Sec-3ero,"TELLO MAYTAHUARI, JIMENA DEL PILAR",Rural,En proceso,En proceso,Satisfactorio,En proceso,En proceso,En proceso,En proceso,Satisfactorio,Satisfactorio,En proceso,Satisfactorio,En proceso,Satisfactorio
506,Julio 2024,64ac1ce7add6a9d39b09b391-Pri-4rto,"TINEO SANCHEZ, THALIA JHOANA",Urbana,NaN,Satisfactorio,Satisfactorio,NaN,NaN,Satisfactorio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
424,Julio 2023,b29b4000-Pri-5nto,"MANRIQUE MURILLO, JOSE LUIS",Rural,Satisfactorio,Satisfactorio,Satisfactorio,En proceso,En proceso,NaN,Satisfactorio,NaN,En proceso,Satisfactorio,Satisfactorio,En proceso,En proceso
461,Julio 2023,b29b6399-Pri-6xto,"ELERA GUERRERO, YERSSON JHAMPOOL",Rural,En inicio,En proceso,Satisfactorio,En proceso,En inicio,NaN,En proceso,NaN,En proceso,En inicio,En proceso,En inicio,En inicio
660,Marzo 2023,0172c480-Pri-5nto,"MESTAS CATCOPARCO, JHAMIR EDER",Urbana,Satisfactorio,Satisfactorio,Satisfactorio,En proceso,Satisfactorio,NaN,Satisfactorio,NaN,Satisfactorio,Satisfactorio,En proceso,Satisfactorio,En proceso
98,Diciembre 2023,b29b1e40-Sec-5nto,"OLIVERA PEniA, RENATO ALEXIS",Rural,Satisfactorio,Satisfactorio,Satisfactorio,Satisfactorio,Satisfactorio,Satisfactorio,Satisfactorio,Satisfactorio,Satisfactorio,Satisfactorio,Satisfactorio,Satisfactorio,Satisfactorio
48,Diciembre 2023,0173c9d6-Pri-5nto,"PAREDES CHURA, MISHEL VANESA",Urbana,Satisfactorio,Satisfactorio,Satisfactorio,En proceso,En proceso,NaN,Satisfactorio,NaN,En inicio,En inicio,En inicio,En proceso,En proceso
667,Marzo 2023,0172c9e1-Pri-6xto,"GAYTAN CUEVA, MARIA SUSANA",Rural,Satisfactorio,En proceso,Satisfactorio,En proceso,En proceso,NaN,En inicio,NaN,Satisfactorio,En inicio,En proceso,En proceso,En inicio
870,Marzo 2024,b29b1d1c2024-Sec-5nto,"BELLIDO SULLCA, CLAUDIA BETZABETH",Rural,Satisfactorio,Satisfactorio,Satisfactorio,En proceso,Satisfactorio,Satisfactorio,En proceso,En proceso,En proceso,Satisfactorio,Satisfactorio,Satisfactorio,Satisfactorio
927,Marzo 2024,b29b48a3x2-Sec-2ndo,"VILLANUEVA BAZAN, NIEVES JHOSELYN",Rural,Satisfactorio,Satisfactorio,Satisfactorio,Satisfactorio,Satisfactorio,Satisfactorio,Satisfactorio,Satisfactorio,Satisfactorio,Satisfactorio,Satisfactorio,Satisfactorio,Satisfactorio
578,Julio 2024,b29b3c342024-Sec-4rto,"LANCHIPA VILDOSO, GIANELLA MILAGROS",Rural,Satisfactorio,En proceso,En proceso,En proceso,Satisfactorio,Satisfactorio,En proceso,Satisfactorio,Satisfactorio,Satisfactorio,En proceso,Satisfactorio,En proceso
821,Marzo 2024,64a33c5eb95521dfd6079755-Sec-5nto,"TELLO FUENTES, THALIA JUDITH",Rural,Satisfactorio,Satisfactorio,Satisfactorio,En proceso,Satisfactorio,Satisfactorio,Satisfactorio,Satisfactorio,Satisfactorio,Satisfactorio,Satisfactorio,Satisfactorio,Satisfactorio
910,Marzo 2024,b29b3d472024-Pri-3ero,"HANAMPA DENOS, LEONCIO",Rural,NaN,Satisfactorio,Satisfactorio,NaN,NaN,Satisfactorio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
809,Marzo 2024,6498eb27fbb0bf758d0ee951-Pri-6xto,"BERAMENDI ESPINOZA, VICTOR ALDAIR",Rural,Satisfactorio,Satisfactorio,Satisfactorio,En proceso,En proceso,NaN,Satisfactorio,NaN,Satisfactorio,Satisfactorio,En proceso,Satisfactorio,En proceso
193,Diciembre 2024,64a33c5eb95521dfd6079755-Sec-4rto,"TELLO FUENTES, THALIA JUDITH",Rural,Satisfactorio,En proceso,En proceso,En proceso,Satisfactorio,En proceso,En proceso,Satisfactorio,Satisfactorio,En proceso,En proceso,Satisfactorio,Satisfactorio
670,Marzo 2023,0172cc42-Pri-5nto,"FERNANDEZ CONTRERAS, SHERLEY PAMELA",Urbana,Satisfactorio,Satisfactorio,Satisfactorio,En proceso,En proceso,NaN,Satisfactorio,NaN,En proceso,En proceso,En inicio,En proceso,En proceso

In [1065]:
replace_dict_soc = {
    'en inicio': 1,
    'en proceso': 2,
    'satisfactorio': 3
}
# Step 1: Select the last 13 columns
last_13_columns = data_socioemocional.iloc[:, -13:]

# Step 2: Convert all values in the last 13 columns to lowercase
last_13_columns_lower = last_13_columns.apply(lambda x: x.str.lower() if x.dtype == 'object' else x)

# Step 3: Replace values in the last 13 columns using the replace_dict
last_13_columns_replaced = last_13_columns_lower.replace(replace_dict_soc)
last_13_columns_replaced = last_13_columns_replaced.fillna(0)

# Step 4: Update the original DataFrame with the modified columns
data_socioemocional.iloc[:, -13:] = last_13_columns_replaced

C:\Users\jange\AppData\Local\Temp\ipykernel_65780\959998812.py:13: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  last_13_columns_replaced = last_13_columns_lower.replace(replace_dict_soc)

In [1066]:
data_socioemocional.sample(15)

,periodo,id_part_grado,participante,ruralidad,Autoconcepto,Autocuidado,Autoestima,Comportamiento prosocial,Comunicación asertiva,Conciencia emocional,Conciencia social,Creatividad,Empatía,Regulación emocional,Resolución de conflictos,Toma de decisiones responsables,Trabajo en equipo
80,Diciembre 2023,b29b0eb1-Pri-3ero,"CHUSHO NUniEZ, MILAGROS VIVIANA",Urbana,0.0,3,3.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
944,Marzo 2024,b29b5e432024-Pri-5nto,"TACO CHURATA, MEYDA ZUSAN",Urbana,3.0,3,3.0,2.0,2.0,0.0,3.0,0.0,3.0,3.0,1.0,2.0,2.0
39,Diciembre 2023,0172d070-Pri-4rto,"PIZARRO PAREDES, LIZBETH DUBERLY",Rural,0.0,3,3.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
762,Marzo 2023,b29b3f66-Pri-4rto,"CALIZAYA CALIZAYA, JENNY ALESSANDRA",Rural,0.0,3,3.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
755,Marzo 2023,b29b3aaa-Sec-4rto,"HUANCAYA CARDENAS, LUZ KAREM",Rural,3.0,3,3.0,2.0,3.0,3.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0
472,Julio 2023,b29b6d0b-Sec-1ero,"ROJAS BROUSSET, JESUS CARMELO",Rural,3.0,3,3.0,3.0,2.0,3.0,2.0,3.0,3.0,3.0,2.0,3.0,2.0
926,Marzo 2024,b29b47192024-Pri-6xto,"VILCAHUAMAN NOLI, GINA MILAGROS",Rural,3.0,3,3.0,2.0,3.0,0.0,3.0,0.0,3.0,3.0,3.0,3.0,2.0
284,Diciembre 2024,b29b64372024-Pri-2ndo,"OLLACHICA HUMPIRI, RUTH MARY",Rural,0.0,2,3.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
448,Julio 2023,b29b57c4-Pri-3ero,"DAVIES GAMARRA, LUCIA ANDREA",Urbana,0.0,2,3.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
627,Julio 2024,b29b676c2024-Sec-3ero,"CHAVEZ APAZA, ELIZABETH",Rural,3.0,3,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0
344,Julio 2023,0173cb97-Pri-6xto,"VILCHEZ MARTINEZ, HELDER JOSE",Rural,3.0,3,3.0,2.0,2.0,0.0,2.0,0.0,1.0,2.0,2.0,2.0,1.0
142,Diciembre 2023,b29b4ff8-Pri-3ero,"PEREZ BUSTAMANTE, MARIA CLAUDIA",Urbana,0.0,2,3.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
500,Julio 2024,64a33c6eb96621dfd6079665-Pri-6xto,"CHACALIAZA ASTOCAZA, JUAN JOSÉ",Rural,3.0,3,3.0,2.0,1.0,0.0,2.0,0.0,2.0,2.0,1.0,1.0,1.0
600,Julio 2024,b29b584c2024-Pri-3ero,"GABINO MENDOZA, SHAMANTA DALLAM",Rural,0.0,3,3.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
351,Julio 2023,0173ce47-Pri-1ero,"URQUIZA RODRIGUEZ, LILIANA ELIZABETH",Rural,0.0,3,3.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [1067]:
data_clima_aula.sample(20)

,periodo,id_part_grado,participante,ruralidad,Aprendizaje completamente interiorizado,Comprensión comprobada y asegurada,Expectativas rigurosas mantenidas,Se crea una cultura positiva y un entorno de aprendizaje,Se establece un entorno de aprendizaje atractivo,Se fomentan relaciones alentadoras y de apoyo,Se valoran los aportes y las ideas de los estudiantes
929,Marzo 2023,b29b51c8-Pri-2ndo,"QUILLA MENDOZA, LYNN",Rural,Satisfactorio,Satisfactorio,Satisfactorio,En proceso,Satisfactorio,Satisfactorio,Satisfactorio
448,Julio 2023,0173cdb4-Pri-4rto,"PEREZ CASTILLO, DANIELA ALEXANDRA",Urbana,En proceso,En proceso,En proceso,En proceso,Satisfactorio,En proceso,En proceso
434,Julio 2023,0172d360-Sec-3ero,"MIRANDA RAMIREZ, CLAUDIA VALENTINA",Urbana,Satisfactorio,En proceso,Satisfactorio,En inicio,En proceso,En proceso,En proceso
1031,Marzo 2024,b29b33702024-Pri-3ero,"ESPINOZA GONZALES, NATALI YOCELIN",Rural,En inicio,En inicio,En proceso,En inicio,En inicio,En inicio,En inicio
278,Diciembre 2024,b29adaf02024-Pri-5nto,"DOMINGUEZ VILLANUEVA, GRACIELA EDILBERTA",Rural,En proceso,En proceso,En proceso,En inicio,En proceso,En proceso,En proceso
431,Julio 2023,0172d1a3-Pri-5nto,"MARMOLEJO CABRERA, ALEXANDRA KARINA",Urbana,En proceso,En proceso,En proceso,En inicio,En proceso,En proceso,En proceso
715,Julio 2024,b29b5b672024-Sec-5nto,"CASTILLO ESTRADA, SIOMARA DE LOS MILAGROS",Rural,En proceso,En proceso,En proceso,En inicio,En proceso,En inicio,En proceso
567,Julio 2023,b29b4719-Sec-1ero,"VILCAHUAMAN NOLI, GINA MILAGROS",Rural,Satisfactorio,En proceso,Satisfactorio,En proceso,En proceso,Satisfactorio,En proceso
127,Diciembre 2023,b29b1328-Pri-5nto,"MONTENEGRO CAJUSOL, LISETH",Urbana,Satisfactorio,En proceso,En proceso,En proceso,En proceso,Satisfactorio,En proceso
1067,Marzo 2024,b29b48a3x2-Sec-2ndo,"VILLANUEVA BAZAN, NIEVES JHOSELYN",Rural,En proceso,En proceso,En inicio,En inicio,En inicio,En proceso,En proceso
543,Julio 2023,b29b3aaa-Sec-4rto,"HUANCAYA CARDENAS, LUZ KAREM",Rural,Satisfactorio,En proceso,En proceso,En proceso,En proceso,En proceso,Satisfactorio
297,Diciembre 2024,b29b1d1c2024-Sec-3ero,"BELLIDO SULLCA, CLAUDIA BETZABETH",Rural,En proceso,En proceso,En proceso,En inicio,En proceso,En proceso,En proceso
908,Marzo 2023,b29b3e4f-Pri-6xto,"LOBATON FLORES, CADY EYTABEL",Urbana,En proceso,Satisfactorio,En inicio,En proceso,Satisfactorio,Satisfactorio,Satisfactorio
435,Julio 2023,01730f3f-Sec-2ndo,"BERRU FLORES, SHIRLEY STEPHANY",Urbana,En proceso,En proceso,En proceso,En inicio,En proceso,En proceso,En proceso
697,Julio 2024,b29b3e4f2024-Pri-5nto,"LOBATON FLORES, CADY EYTABEL",Urbana,En proceso,En proceso,En proceso,En proceso,En inicio,En proceso,En proceso
925,Marzo 2023,b29b4a7d-Pri-5nto,"ALCANTARA PACASI, NENA YASMIN",Urbana,En proceso,Satisfactorio,En proceso,En proceso,Satisfactorio,En proceso,En proceso
962,Marzo 2023,b29b6c11-Pri-4rto,"REMAYCUNA VASQUEZ, GLADYS",Rural,Satisfactorio,Satisfactorio,En proceso,Satisfactorio,Satisfactorio,Satisfactorio,Satisfactorio
108,Diciembre 2023,81fe4fc0-Pri-3ero,"FRANCO CRISTOBAL, GIULIANA LOIDA",Rural,Satisfactorio,Satisfactorio,En proceso,En proceso,Satisfactorio,Satisfactorio,Satisfactorio
310,Diciembre 2024,b29b35f62024-Sec-1ero,"BOZA CCOYLLAR, BRANDO",Rural,En proceso,En proceso,Satisfactorio,En inicio,Satisfactorio,En proceso,En proceso
267,Diciembre 2024,64a9b66ffff19cf3f01b8ec-Pri-4rto,"QUISOCOLA CHAMPI, GABRIELA",Rural,En inicio,En proceso,En proceso,En proceso,En proceso,Satisfactorio,En proceso

In [1068]:
replace_dict_cli = {
    'en inicio': 1,
    'en proceso': 2,
    'satisfactorio': 3,
}
# Step 1: Select the last 22 columns
last_7_columns = data_clima_aula.iloc[:, -7:]

# Step 2: Convert all values in the last 22 columns to lowercase
last_7_columns_lower = last_7_columns.apply(lambda x: x.str.lower() if x.dtype == 'object' else x)

# Step 3: Replace values in the last 22 columns using the replace_dict
last_7_columns_replaced = last_7_columns_lower.replace(replace_dict_cli)
last_7_columns_replaced = last_7_columns_replaced.fillna(0)

# Step 4: Update the original DataFrame with the modified columns
data_clima_aula.iloc[:, -7:] = last_7_columns_replaced

C:\Users\jange\AppData\Local\Temp\ipykernel_65780\2669337795.py:13: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  last_7_columns_replaced = last_7_columns_lower.replace(replace_dict_cli)

In [1069]:
data_clima_aula.sample(10)

,periodo,id_part_grado,participante,ruralidad,Aprendizaje completamente interiorizado,Comprensión comprobada y asegurada,Expectativas rigurosas mantenidas,Se crea una cultura positiva y un entorno de aprendizaje,Se establece un entorno de aprendizaje atractivo,Se fomentan relaciones alentadoras y de apoyo,Se valoran los aportes y las ideas de los estudiantes
728,Julio 2024,b29b65cd2024-Pri-5nto,"ZAPATA SOSA, LUIS JUNIOR",Urbana,2,2,2,1,2,2,3
388,Julio 2023,0172b9ee-Sec-3ero,"SORIA HUANCAS, JOISY SHIRLEY",Rural,2,2,2,2,2,2,2
170,Diciembre 2023,b29b3bb3-Sec-2ndo,"LOPEZ VILELA, JOSE AUGUSTO",Urbana,3,3,3,1,2,3,3
226,Diciembre 2023,b29b617a-Sec-5nto,"BENITO PILCO, GLADYS",Rural,3,3,3,2,2,3,3
894,Marzo 2023,b29b3aaa-Sec-2ndo,"HUANCAYA CARDENAS, LUZ KAREM",Rural,3,3,2,2,2,2,3
355,Diciembre 2024,b29b5e432024-Pri-5nto,"TACO CHURATA, MEYDA ZUSAN",Urbana,2,2,2,1,2,2,2
259,Diciembre 2024,64a33c5eb95521dfd6079755-Sec-5nto,"TELLO FUENTES, THALIA JUDITH",Rural,1,2,2,2,2,1,1
124,Diciembre 2023,b29b117e-Pri-4rto,"ALBINO ARBAIZA, JULISSA ELENA",Rural,2,3,2,2,2,2,2
1086,Marzo 2024,b29b5ed12024-Sec-2ndo,"RAMOS PINTO, LUIS ENRIQUE",Rural,1,2,1,1,2,1,2
638,Julio 2024,64a33c5eb95521dfd6079755-Sec-5nto,"TELLO FUENTES, THALIA JUDITH",Rural,1,2,1,1,1,1,2

In [1070]:
data_clima_aula.shape

(1105, 11)

In [1071]:
data_academico.to_csv("..\\data\\academico_pdl.csv", index=False)
data_socioemocional.to_csv('..\\data\\socioemocional_pdl.csv', index=False)
data_clima_aula.to_csv('..\\data\\clima_aula_pdl.csv', index=False)